#!/usr/bin/env bash

set -euo pipefail

main() {
	curl "https://releases.hashicorp.com/packer/0.11.0/packer_0.11.0_linux_amd64.zip" > packer.zip

	unzip packer.zip -d "/usr/bin"

	pip install ansible
}

main "$@"
